name: "Terraform Guided Run"

on:
  push:
    branches:
      - '**' # This targets EVERY branch you push to, not just main

permissions:
  contents: read
  id-token: write

env:
  TF_VAR_billing_account_id: ${{ secrets.GCP_BILLING_ACCOUNT_ID }}
  TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}

jobs:
  terraform-pipeline:
    name: "Terraform Core Engine"
    runs-on: ubuntu-latest
    environment: sandbox-gate # This forces GitHub to pause before running the steps below
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/785454820173/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
        service_account: 'tf-bootstrap@dark-gateway-398321.iam.gserviceaccount.com'

    - name: Terraform Init
      run: terraform init

    # Generates the execution blueprint so you can review it in the logs
    - name: Terraform Plan
      run: terraform plan -input=false

    # Because you already manually approved the job to start, this executes immediately after the plan logs output
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
